version: '3.8'

services:
  clms-database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=clms
    ports:
      - "5001:5432"
    volumes:
      - clms-database-volume:/var/lib/postgresql/data

volumes:
  clms-database-volume: