spring:
  application:
    name: teamiq-api

  datasource:
    url: jdbc:postgresql://localhost:5001/teamiq
    username: root
    password: changeme

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  web:
    resources:
      static-locations:
        - file:src/main/resources/static/
        - classpath:/static/

teamiq:
  password:
    strength: 10
